apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greet-devship-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - "greet.devship.localhost"
  rules:
    - host: "greet.devship.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: greet-devship-svc
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: greet-devship-svc
spec:
  type: LoadBalancer
  selector:
    app: greet-devship
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      name: 80-8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-devship
  labels:
    app: greet-devship
spec:
  selector:
    matchLabels:
      app: greet-devship
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: greet-devship
    spec:
      containers:
      - name: greet-devship
        image: registry.devship.localhost:5000/k8s-spring-greet:1.0.0
        ports:
          - containerPort: 8080
            name:  greet-devship
